import React, { useState } from 'react'
import Head from 'next/head'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'
import { supabase } from '../utility/supabaseClient'
import { useRouter } from 'next/router'

export default function Home() {
 
  const [user, setUser] = useState(supabase.auth.user());
  const router = useRouter()


  useEffect(() =>{
  if(user){
    router.push('/UserPage')
  }
  },[user])


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      
     
    </div>
  )
}





